omniauth:
  facebook:
    key: '526887810770201'
    secret: db6c7f947b4b40862e54340d6a1af3c2
  vkontakte:
    key: '4411921'
    secret: aBamPOFuJoxwwPAWChgJ
  twitter:
    key: L9hNcEDguODL3SYoU3hpyzroY
    secret: L7nz5K69eQ1RcKlSl9zQoUmWlSchpJLFUiW1uGwC2JZ9QE1e4n
