# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  host: localhost
  pool: 5
  username: max_abramchuck
  password: 123
  timeout: 5000

test:
  adapter: postgresql
  database: project_test
  pool: 5
  timeout: 5000
  username: max_abramchuck
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: foo
  port: 5432
  host: foobar.amazonaws.com
  username: max_abramchuck
  password: 123