# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c44a56d72259203e87fc3a10c5cbf32bde91adfbdf756ad7c74fa474cb7539d1f23f26a2300dcc072ebfa7db39248ae21157f974495ff7efe5ea566a6485d1b3

test:
  secret_key_base: d5bfc2b36ec1107cdaa2e43a255288b9fb0f2b8f8c47f2e1f31c2e021846bb2bb6338c4c26948fdf64a0303ee9860266180513c8b33870d33c7425d844b15ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
